### ISSUE TITLE
Inconsistent Signer Behavior

### ISSUE THREAD

**Issue by con5cience** [strangelove-ventures/horcrux#159]
Hi there,

I'm trying to implement a Horcrux POC that would mimic my Production architecture with Quicksilver Testnet + Cosmovisor. I have three Sentry nodes up and synced and I'm on Horcrux v3. Processes are all running in plain Kubernetes, no RBAC, no network policies, TCP connectivity has all been tested with `telnet` and the processes can all talk to each other just fine.

### Scenario 1
When I plug each individual Signer into a dedicated Sentry, nothing happens.

Signer configs, `chainNodes.privValAddr` changes depending on the node:
```
signMode: threshold
thresholdMode:
  threshold: 2
  cosigners:
    - shardID: 1
      p2pAddr: tcp://quicksilver-testnet-signer-0.quicksilver.svc.cluster.local:2222
    - shardID: 2
      p2pAddr: tcp://quicksilver-testnet-signer-1.quicksilver.svc.cluster.local:2222
    - shardID: 3
      p2pAddr: tcp://quicksilver-testnet-signer-2.quicksilver.svc.cluster.local:2222
  grpcTimeout: 1000ms
  raftTimeout: 1000ms
chainNodes:
  - privValAddr: tcp://quicksilver-testnet-sentry-[0,1,2].quicksilver.svc.cluster.local:1234
debugAddr: ''
```

Sentry logs:
```
quicksilver-testnet-sentry-0 2:26AM INF running app args=["start","--home","/.quicksilverd","--moniker","FooBar-0"] module=cosmovisor path=/.quicksilverd/cosmovisor/genesis/bin/quicksilverd
quicksilver-testnet-sentry-0 2:27AM INF starting node with ABCI Tendermint in-process
quicksilver-testnet-sentry-0 2:27AM INF service start impl=multiAppConn module=proxy msg={}
quicksilver-testnet-sentry-0 2:27AM INF service start connection=query impl=localClient module=abci-client msg={}
quicksilver-testnet-sentry-0 2:27AM INF service start connection=snapshot impl=localClient module=abci-client msg={}
quicksilver-testnet-sentry-0 2:27AM INF service start connection=mempool impl=localClient module=abci-client msg={}
quicksilver-testnet-sentry-0 2:27AM INF service start connection=consensus impl=localClient module=abci-client msg={}
quicksilver-testnet-sentry-0 2:27AM INF service start impl=EventBus module=events msg={}
quicksilver-testnet-sentry-0 2:27AM INF service start impl=PubSub module=pubsub msg={}
quicksilver-testnet-sentry-0 2:27AM INF service start impl=IndexerService module=txindex msg={}
quicksilver-testnet-sentry-0 2:27AM INF service start impl=SignerListenerEndpoint module=privval msg={}
quicksilver-testnet-sentry-0 2:27AM INF SignerListener: Listening for new connection module=privval
quicksilver-testnet-sentry-0 2:27AM INF SignerListener: Blocking for connection module=privval
quicksilver-testnet-sentry-0 2:27AM INF SignerListener: Connected module=privval
```

It appears to be acting like none of the signing requests are going through to the signers. The behavior appears to be expected when signing isn't happening at all based on what I've managed to sift out of Tendermint issues like [this one](https://github.com/tendermint/tendermint/issues/3455) but ultimately I'm not sure.

Signer logs all look the same, the target address of course changes depending on which Signer is pointed at which Sentry:
```
horcrux-quicksilver-testnet-signer-2 I[2023-06-09|15:12:01.188] Horcrux Validator                            module=validator mode=threshold priv-state-dir=/.horcrux/state                                                                          
horcrux-quicksilver-testnet-signer-2 I[2023-06-09|15:12:01.196] service start                                module=validator msg="Starting CosignerRaftStore service" impl=CosignerRaftStore                                                        
horcrux-quicksilver-testnet-signer-2 I[2023-06-09|15:12:01.196] Local Raft Listening                         module=validator port=2222                                                                                                              
horcrux-quicksilver-testnet-signer-2 I[2023-06-09|15:12:01.199] debug-addr not defined; debug server disabled module=debugserver                                                                                                                     
horcrux-quicksilver-testnet-signer-2 I[2023-06-09|15:12:01.200] service start                                module=validator msg="Starting RemoteSigner service" impl=RemoteSigner                                                                  
horcrux-quicksilver-testnet-signer-2 I[2023-06-09|15:12:01.219] Connected to Sentry                          module=validator address=tcp://quicksilver-testnet-sentry-2.quicksilver.svc.cluster.local:1234
```

### Scenario 2
If I hand off this config to all the Signers, with all of the Sentries included in the `chainNodes` list:
```
signMode: threshold
thresholdMode:
  threshold: 2
  cosigners:
    - shardID: 1
      p2pAddr: tcp://quicksilver-testnet-signer-0.quicksilver.svc.cluster.local:2222
    - shardID: 2
      p2pAddr: tcp://quicksilver-testnet-signer-1.quicksilver.svc.cluster.local:2222
    - shardID: 3
      p2pAddr: tcp://quicksilver-testnet-signer-2.quicksilver.svc.cluster.local:2222
  grpcTimeout: 1000ms
  raftTimeout: 1000ms
chainNodes:
  - privValAddr: tcp://quicksilver-testnet-sentry-0.quicksilver.svc.cluster.local:1234
  - privValAddr: tcp://quicksilver-testnet-sentry-1.quicksilver.svc.cluster.local:1234
  - privValAddr: tcp://quicksilver-testnet-sentry-2.quicksilver.svc.cluster.local:1234
debugAddr: ''
```

1. The Signer cluster connects to **one** Sentry. The Sentry pulls blocks, the Signer cluster signs blocks. Everything appears to work, except the other Sentries sit there waiting for remote validators to connect and they don't sync at all, which is not ideal.
2. The Signer cluster always picks the last Sentry in the list, even when I kill all the Signer nodes at the same time, multiple times in a row. I would expect to see the cluster pick a different Sentry on restart, and/or I would expect the individual Signers to each pick a different Sentry (potentially unfounded expectation informed by years of working with cluster-y softwares).
3. Killing the Sentry causes the Signer cluster to stop signing until the Sentry comes back. The Signer cluster does not try to connect to a different Sentry when the connection is lost.

What am I doing wrong? Any help would be super appreciated. If I've missed a glaringly obvious thing in the docs about how this is all supposed to work, feel free to just drop the link on my face. Ideally I'd like to have a full mesh or 1:1 arrangement between Sentries and Signer processes for maximum fault tolerance.

Thanks in advance.
