### ISSUE TITLE
Leader election fails with v3.0.0

### ISSUE THREAD

**Issue by m8nky** [strangelove-ventures/horcrux#166]
**Context:**
Current leader is node ID 1. Trying to pass the Horcrux leader to a different co-signer via CLI.

```bash
horcrux elect
# OR
horcrux elect 2
```

Config:
```yaml
signMode: threshold
thresholdMode:
  threshold: 2
  cosigners:
  - shardID: 1
    p2pAddr: tcp://10.30.0.1:2224
  - shardID: 2
    p2pAddr: tcp://10.30.1.1:2224
  - shardID: 3
    p2pAddr: tcp://10.30.1.2:2224
  grpcTimeout: 1000ms
  raftTimeout: 1000ms
chainNodes:
- privValAddr: tcp://10.30.1.1:1235
- privValAddr: tcp://10.30.1.2:1235
debugAddr: ""
```

**Current behavior:**
```
Broadcasting to address: multi:///10.30.0.1:2224,10.30.1.1:2224,10.30.1.2:2224
Error: dialing failed: failed to build resolver: parse "10.30.0.1:2224": first path segment in URL cannot contain colon
```

**Expected behavior:**
New leader should be selected.
